Repository honganhcs/c-slang, pull requests merged in 2023-03, with the labels that each got.

#8 feat: parse `<additive-expression>` and `<constant-expression>`
  README.md
  package.json
  src/editors/ace/modes/source.ts
  src/lang/C.g4
  src/lang/C.interp
  src/lang/C.tokens
  src/lang/CLexer.interp
  src/lang/CLexer.tokens
  src/lang/CLexer.ts
  src/lang/CListener.ts
  src/lang/CParser.ts
  src/lang/CVisitor.ts
  src/lang/Calc.g4
  src/lang/Calc.interp
  src/lang/Calc.tokens
  src/lang/CalcLexer.interp
  src/lang/CalcLexer.tokens
  src/lang/CalcLexer.ts
  src/lang/CalcListener.ts
  src/lang/CalcParser.ts
  src/lang/CalcVisitor.ts
  src/parser/parser.ts
  src/repl/repl.ts
  src/types.ts
  yarn.lock
Labels: feat

#11 fix: fix empty program body bug in `parser.ts`
  src/parser/parser.ts
Labels: fix

#13 feat: parse `<cast-expression>`
  src/lang/C.g4
  src/lang/C.interp
  src/lang/CParser.ts
  src/parser/parser.ts
  src/utils/operators.ts
Labels: feat

#9 feat: evaluate `<additive-expression>`
  src/interpreter/interpreter.ts
  src/utils/expressions.ts
  src/utils/operators.ts
  src/utils/rttc.ts
Labels: feat

#19 feat: evaluate `<constant-statement>`
  src/interpreter/interpreter.ts
  src/utils/expressions.ts
  src/utils/statements.ts
Labels: feat

#20 feat: parse `<declaration>`
  src/interpreter/interpreter.ts
  src/lang/C.g4
  src/lang/C.interp
  src/lang/CListener.ts
  src/lang/CParser.ts
  src/lang/CVisitor.ts
  src/parser/parser.ts
  src/utils/astMaps.ts
  src/utils/operators.ts
Labels: feat

#21 fix: fix node type in evaluateBlockStatement()
  src/interpreter/interpreter.ts
Labels: fix

#27 feat: parse `<statement>`
  src/lang/C.g4
  src/lang/C.interp
  src/lang/CListener.ts
  src/lang/CParser.ts
  src/lang/CVisitor.ts
  src/parser/parser.ts
Labels: feat

#28 fix: add evaluate function for SequenceExpression
  src/interpreter/interpreter.ts
  src/parser/parser.ts
Labels: fix

#29 feat: evaluate `<declaration>`
  .github/workflows/nodejs.yml
  src/createContext.ts
  src/evaluators/declarations.ts
  src/evaluators/expressions.ts
  src/evaluators/operators.ts
  src/evaluators/statements.ts
  src/interpreter/interpreter.ts
  src/runner/sourceRunner.ts
  src/utils/astMaps.ts
  src/utils/expressions.ts
  src/utils/statements.ts
  src/utils/stringify.ts
Labels: feat

#30 feat: complete `<iteration-expression>`
  src/evaluators/expressions.ts
  src/evaluators/statements.ts
  src/interpreter/interpreter.ts
  src/validator/validator.ts
Labels: feat

#36 fix: parse `<selection-statement>`
  package.json
  src/parser/parser.ts
Labels: fix

#39 feat: parse `<function-definition>`
  src/parser/parser.ts
Labels: feat

#41 feat: parse `<postfix-expression>` (array access and function call)
  src/parser/parser.ts
Labels: feat

#43 feat: evaluate `<jump-statement>` and `<function-definition>`
  src/createContext.ts
  src/evaluators/declarations.ts
  src/evaluators/expressions.ts
  src/evaluators/statements.ts
  src/interpreter/interpreter.ts
Labels: feat

#45 feat: evaluate `<postfix-expression>`
  src/createContext.ts
  src/evaluators/declarations.ts
  src/evaluators/expressions.ts
  src/evaluators/statements.ts
  src/interpreter/interpreter.ts
Labels: feat

#47 feat: parse `<cast-expression>` and `<declaration>`
  src/lang/C.g4
  src/lang/C.interp
  src/lang/CListener.ts
  src/lang/CParser.ts
  src/lang/CVisitor.ts
  src/parser/parser.ts
Labels: feat

#48 feat: add `main()` at the end of program and parse array initializer
  src/parser/parser.ts
Labels: feat

#50 feat: parse array and pointer params for `<function-definition>`
  src/lang/C.g4
  src/lang/C.interp
  src/lang/CListener.ts
  src/lang/CParser.ts
  src/lang/CVisitor.ts
  src/parser/parser.ts
Labels: fix, feat

#52 fix: handle array dimension
  .github/workflows/deploy-docs.yml
  src/evaluators/declarations.ts
  src/types.ts
Labels: fix

#54 feat: evaluate `<cast-expression>`
  src/createContext.ts
  src/evaluators/declarations.ts
  src/evaluators/expressions.ts
  src/interpreter/interpreter.ts
  src/types.ts
Labels: feat

#55 feat: implement a basic heap for memory management
  src/createContext.ts
  src/evaluators/declarations.ts
  src/evaluators/expressions.ts
  src/heap.ts
  src/interpreter/interpreter.ts
  src/types.ts
Labels: feat
